- hosts: localhost
  tasks:
  - name: Check if docker is installed
    become: true
    command: docker --version
    register: docker_check

  - name: if docker is not installed
    ignore_errors: True
    become: true
    command: sudo apt-get -y install docker.io
    when: docker_check.stdout.find('not found') != -1

  - name: check if jenkins container exists
    become: true
    command: sudo docker start DevOpsCICD
    register: container_check

#  - name: if container does not exist
#    command: create & config jenkins container
#    become: true
#    when: container_check.stdout.find('Error') != -1

  - name: pull from git
    become: true
    git:
      repo: https://github.com/Vortechs299/DevOpsCI.git
      dest: /home/gyropyro/Desktop/DevOpsCI
      update: yes
      version: master

  - name: start Node server
    command: node server.js

  - name: open browser on localhost:3001
    command: xdg-open localhost:3001

  - name: open jenkins web app
    command: xdg-open http://localhost:8080
